[book]
authors = ["Jacky Song"]
language = "en"
multilingual = false
src = "src"
title = "Vim Personal Docs"

[output.html]
git-repository-url = "https://github.com/helio-fm/helio-workstation/tree/develop/Docs"
default-theme = "navy"
curly-quotes = true
